spring:
  application:
    name: authorization-server
  main:
    web-application-type: servlet

  session:
    timeout: 10s
    redis:
      namespace: authorization:session
      configure-action: none
      repository-type: indexed
      cleanup-cron: 0 * * * * *
      flush-mode: on-save
      save-mode: on-set-attribute

  data:
    redis:
      repositories:
        enabled: true
      host: localhost
      port: 6379
      timeout: 3000
      database: 0
      client-type: lettuce

  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/sign-in/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true

logging:
  level:
    org:
      springframework:
        web: debug
        security: trace

management:
  server:
    port: 8888


server:
  port: 8080

